version: '3.9'

services:
  spend_bot:
    networks:
        - spend_bot_net
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spend_bot
    env_file:
      - ./.env
    ports:
      - "80:80"
    restart: always
    entrypoint: ["python3", "-m", "spend_bot.bot"]

networks:
  spend_bot_net:
    name: spend_bot_net
