version: '3.9'

services:
  spend_bot:
    networks:
        - spent_bot_net
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spend_bot
    env_file:
      - ./.env
    ports:
      - "0000:0000"
    restart: always
    entrypoint: ["python3", "-m", "spend_bot.bot"]

networks:
  web_network:
    name: spent_bot_net
